apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-svc
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.application.name }}
    managed-by: helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.application.name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
